### ISSUE TITLE
User should be able to add product to customer order

### ISSUE THREAD

**Issue by gregkorte** [Funky-Chickens/Bangazon-CLI#5]
**Given** a customer has been made active in the program
**When** the user selects the option to add a product to the active customer's order
**Then** the user should be prompted with a numbered list of all products
**And** when one is chosen, the product should be added to an order for the active customer

- [x] Test GET all products function

- [x] GET all products and print to the console

- [x] Prompt user for # of product to add to order, add options of exit, complete order(goes to payment)

- [x] Test GET function for the user id on open orders.

- [x] Check to see if there is an open order with that user id or not (GET)

- [x] Test the POST function for the join table and also the POST function for the order table.

- [x] If order is already open with that user id, use GET info to POST product id  and order id to the join table only.

- [x] If there is no open order with that user id, then POST {productid, userid} to order table and {orderid, productid} to the join table

> **Pro tip**: To make it easier to add multiple products, when the user selects a product to add to the customer's order, display the menu of products again. Make sure the last option provides the option to go back to main menu.

```bash
1. Diapers
2. Case of Cracking Cola
3. Bicycle
4. AA Batteries
...
9. Done adding products
```

**Comment by An-AngryBear** [comment]
- [ ] update quantity
